# Generated by Django 5.1.2 on 2025-01-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
